### ISSUE TITLE
Kustomize version 4.5.5 unknown flag --load_restrictor

### ISSUE THREAD

**Issue by elliottminns** [helmfile/chartify#35]
It appears that the Kustomize version parsing is no longer working as expected. When running this on helmfile, it throws the following error message:

```
 COMMAND:
  kustomize -o /tmp/chartify146105240/foo/bar/templates/kustomized.yaml build --load_restrictor=none --enable_alpha_plugins /tmp/chartify146105240/foo/bar
  
OUTPUT:
  Error: unknown flag: --load_restrictor]
```

It looks like Kustomize changed the version string format in for the command `version --short` which is causing this issue. It may be worthwhile to default to version 4 instead of the current behavior which is to default to version 3 in the case that the version string is not parsed correctly.

**Comment by zekena2** [comment]
The issue still exists and kustomize v4 doesn't work.

**Comment by marcusramberg** [comment]
Also, to follow up, it seems that kustomize v5 has deprecated the 'short' param, so chartify should probably be parsing the json output instead for more compatibility.

**Comment by yxxhero** [comment]
see: https://github.com/helmfile/chartify/pull/55
