### ISSUE TITLE
Can I move this repository to the Helmfile org?

### ISSUE THREAD

**Issue by mumoshu** [helmfile/chartify#42]
Can we move this repository to https://github.com/helmfile so that not only me but also all Helmfile maintainers can co-maintain this project?
We can generally say that the more hands there are, the more the project will be maintained well.
Also, to be clear, note that I'm one of the maintainers of the Helmfile project and Helmfile is the biggest public dependent of this project, as far as I know. I believe those two points would justify the move to the Helmfile org if moving it to somewhere is okay in the first place.

**Comment by yxxhero** [comment]
:)

**Comment by mumoshu** [comment]
I've just transferred the repo 👍
