### ISSUE TITLE
Add support for import-values of dependencies

### ISSUE THREAD

**Issue by AntonioAlfrz** [helmfile/chartify#60]
Chartify does not seem to take into account the possibility of a dependency to have import-values:

https://github.com/helmfile/chartify/blob/master/requirements.go#L15

More info: https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies

**Comment by yxxhero** [comment]
@AntonioAlfrz  PR is welcome.

**Comment by lucasfcnunes** [comment]
Isn't this already fixed by #61?
